# -*- coding: utf-8 -*-
"""Self made  ARIMA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1actTg2fdHpHF9KUKQlOu2ooUZI7boOJb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import rcParams
from datetime import datetime
from pandas.plotting import autocorrelation_plot
from statsmodels.tsa.arima_model import ARIMA
from sklearn.metrics import mean_squared_error

dateparse = lambda dates: pd.datetime.strptime('2019-12-27 00:00:00','%Y-%m-%d %H:%M:%S')

series = pd.read_csv('device41.csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=dateparse)
X = series.values
size = int(len(X) * 0.7)
train, test = X[0:size], X[size:len(X)]
history = [x for x in train]
predictions = list()

for t in range(len(test)):
    model = ARIMA(history, order=(5,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    predictions.append(yhat)
    obs = test[t]
    history.append(obs)
    # print('predicted=%f, expected=%f' % (yhat, obs))

error = mean_squared_error(test, predictions)
print('Test MSE: %.3f' % error)
# plot
plt.plot(test)
plt.plot(predictions, color='red')
plt.show()



